// Assemble the audit report markdown and write to primary + (optional) mirror.
// Usage: build-report.mjs [--out <path>]
//   inputs (env vars override):
//     FIGMA_JSON     /tmp/lotus-figma-tokens.json
//     IOS_COLORS     /tmp/ios-colors.json
//     PARITY_JSON    /tmp/colour-parity.json
//     SCAN_JSON      /tmp/ios-scan.json
//   output:
//     primary:       <lotus-repo>/audits/ios/YYYY-MM-DD.md (relative to this script)
//     mirror:        $LOTUS_AUDIT_MIRROR/YYYY-MM-DD.md (if set + dir exists)
//     index update:  Olly's vault _Index.md (only when mirror is in his vault)
import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const figma  = JSON.parse(readFileSync(process.env.FIGMA_JSON   || '/tmp/lotus-figma-tokens.json', 'utf8'));
const ios    = JSON.parse(readFileSync(process.env.IOS_COLORS   || '/tmp/ios-colors.json', 'utf8'));
const parity = JSON.parse(readFileSync(process.env.PARITY_JSON  || '/tmp/colour-parity.json', 'utf8'));
const scan   = JSON.parse(readFileSync(process.env.SCAN_JSON    || '/tmp/ios-scan.json', 'utf8'));

// --out override
let outOverride = null;
const outIdx = process.argv.indexOf('--out');
if (outIdx !== -1 && process.argv[outIdx + 1]) outOverride = process.argv[outIdx + 1];

const fc = name => figma.collections.find(c => c.collection === name);
const colourSem = fc('Colour');
const padding = fc('Padding');
const radius = fc('Corner Radius');

const iosSpacing = [['spacingNone',0],['spacingXXXSmall',2],['spacingXXSmall',4],['spacingXSmall',8],['spacingSemiSmall',10],['spacingSmall',12],['spacingMedium',16],['spacingXMedium',20],['spacingLarge',24],['spacingXLarge',32],['spacingXXLarge',40],['spacingXXXLarge',70]];
const iosRadius = [['radiusNone',0],['radiusXXSmall',1],['radiusXSmall',4],['radiusSmall',8],['radiusXMedium',12],['radiusMedium',16],['radiusXLarge',20],['radiusLarge',24],['radiusFull',32]];
const iosTypography = [['h1Nunito','NunitoSans-Bold',32],['h1Poppins','Poppins-Bold',32],['h2Nunito','NunitoSans-Bold',24],['h2PoppinsLight','Poppins-Light',23],['h2Poppins','Poppins-Regular',24],['h2PoppinsBold','Poppins-SemiBold',24],['h3','NunitoSans-Regular',20],['bodyLarge','NunitoSans-Regular',18],['bodyLargeBold','NunitoSans-Bold',18],['bodyMedium','NunitoSans-Regular',16],['bodyMediumBold','NunitoSans-Bold',16],['bodySmall','NunitoSans-Regular',14],['bodySmallMedium','NunitoSans-Regular medium',14],['bodySmallBold','NunitoSans-Bold',14],['caption','NunitoSans-Regular',12],['captionBold','NunitoSans-Bold',12],['micro','NunitoSans-Regular',10],['microBold','NunitoSans-Bold',10],['sfSemiBoldFont','System semibold',15],['sfRegularFont','System regular',15]];

// Padding parity
const padRows = [];
for (const v of padding.vars) {
  padRows.push({ figma: v.name, figmaVal: Object.values(v.valuesByMode)[0]?.resolved, iosName: null, iosVal: null });
}
for (const [n, val] of iosSpacing) {
  const fig = padRows.find(r => r.figmaVal == val && !r.iosName);
  if (fig) { fig.iosName = n; fig.iosVal = val; }
  else padRows.push({ figma: null, figmaVal: null, iosName: n, iosVal: val });
}
const radRows = [];
for (const v of radius.vars) radRows.push({ figma: v.name, figmaVal: Object.values(v.valuesByMode)[0]?.resolved, iosName: null, iosVal: null });
for (const [n, val] of iosRadius) {
  const fig = radRows.find(r => r.figmaVal == val && !r.iosName);
  if (fig) { fig.iosName = n; fig.iosVal = val; }
  else radRows.push({ figma: null, figmaVal: null, iosName: n, iosVal: val });
}

const cs = parity.summary;
const padStatus = r => {
  if (r.figmaVal === r.iosVal && r.figma && r.iosName) return '✅ match';
  if (r.figma && !r.iosName) return '❌ missing in iOS';
  if (!r.figma && r.iosName) return '⚠️ iOS-only';
  return '❌ mismatch';
};

const today = new Date().toISOString().slice(0, 10);
const lines = [];
const out = (s='') => lines.push(s);

// Helper: enrich rows with iOS raw/displayed hex
const iosByName = Object.fromEntries(ios.map(c => [c.name.toLowerCase().replace(/[-\s]/g,''), c]));
function enrichIos(asset) {
  return iosByName[asset.toLowerCase().replace(/[-\s]/g,'')];
}

out(`# Lotus — iOS Audit (${today})`);
out('');
out(`*Auto-generated by \`/lotus-audit-ios\`. Source of truth: [Lotus design system Figma file](https://www.figma.com/design/YkS9s6Cz3EYdbr5UThzUKP/Lotus---Design-System).*`);
out('');
out(`*iOS commit:* \`${scan.iosCommit.slice(0, 7)}\` · *Figma snapshot:* \`${figma.generatedAt}\` · *Files scanned:* ${scan.totals.files}`);
out('');
out('> [!info] Colour-space note');
out('> iOS asset catalogs at JustPark are tagged `display-p3`. Figma, Android (`Color(0xFF…)`), and Web (CSS hex) all default to **sRGB**. The iOS values in this report are converted from P3 → sRGB before comparison so the numbers match what users actually see on a P3-capable iPhone. The "raw" values stored in the asset catalog are listed alongside for transparency.');
out('');
out('---');
out('');

// Summary
const ratio = (scan.totals.ratio * 100).toFixed(0);
out('## Summary');
out('');
out('> [!summary]');
out(`> Lotus tokenisation across the iOS app sits at **${ratio}%** (${scan.totals.tokenised} tokenised refs vs ${scan.totals.violations} violations across ${scan.totals.files} UI-styling files). The headline drag is **${scan.totals.legacy} references** to the legacy \`jp*\` colour palette in \`Shared/JPCore/Extensions/UIColor+JP.swift\` — concentrated in legacy UIKit screens that pre-date Lotus. New SwiftUI flows (Home, On-Demand, Auth) are 80–90% tokenised; legacy UIKit areas (Shared & Infra, Account, Widget) are below 10%. Token-parity vs Figma is messy: of ${cs.totalFigmaSemantic} matchable Figma semantic colours, **${cs.match}** match cleanly, ${cs.mismatch} drift in value, ${cs.darkOnlyMismatch} match light but disagree in dark, and ${cs.missingIos} Figma tokens have no iOS equivalent at all (mostly the new \`Tertiary\`, \`Tapped\`, and \`Link-*\` semantic layer Figma added without iOS catching up). The brand green \`Brand.JustparkGreen\` is stored as bytes \`0x23 0xA4 0x37\` but rendered through P3 displays as \`#00A71D\` — visibly more saturated than the Figma reference \`#23A437\`. The single most critical bug — \`Action.PrimaryDefault\` resolving to \`#008000\` — is still in the asset catalog.`);
out('');
out('---');
out('');

// Token parity
out('## Token parity (Figma ↔ iOS)');
out('');
out('### Colours');
out('');
out(`Figma's semantic Colour collection has ${colourSem.vars.length} variables across Light + Dark modes. iOS has ${ios.length} colorsets in \`Lotus-Colour-Pallet\`. iOS values are shown as **displayed sRGB** (the P3-converted equivalent) with the **raw bytes** in parentheses for transparency.`);
out('');
out('| Status | Count |');
out('|---|---|');
out(`| ✅ Both modes match | ${cs.match} |`);
out(`| ⚠️ Light matches, Dark differs | ${cs.darkOnlyMismatch} |`);
out(`| ❌ Value mismatch | ${cs.mismatch} |`);
out(`| ❌ Missing in iOS | ${cs.missingIos} |`);
out(`| ⚠️ iOS-only (no Figma equivalent) | ${cs.iosOnlySemantic} |`);
out('');
out('#### Mismatches (light + dark differ)');
out('');
out('| Figma | iOS asset | Figma Light | Figma Dark | iOS Light (displayed/raw) | iOS Dark (displayed/raw) |');
out('|---|---|---|---|---|---|');
for (const r of parity.rows.filter(x => x.status === 'mismatch')) {
  const e = enrichIos(r.iosAsset);
  const lDisp = e?.light || '—', lRaw = e?.lightRaw || '—';
  const dDisp = e?.dark || '—', dRaw = e?.darkRaw || '—';
  out(`| ${r.figmaName} | ${r.iosAsset} | \`${r.figmaLight}\` | \`${r.figmaDark || '—'}\` | \`${lDisp}\` (raw \`${lRaw}\`) | \`${dDisp}\` (raw \`${dRaw}\`) |`);
}
out('');
out('#### Light matches, Dark mismatches');
out('');
out('| Figma | iOS asset | Light (✅) | Figma Dark | iOS Dark |');
out('|---|---|---|---|---|');
for (const r of parity.rows.filter(x => x.status === 'dark-only-mismatch')) {
  out(`| ${r.figmaName} | ${r.iosAsset} | \`${r.figmaLight}\` | \`${r.figmaDark}\` | \`${r.iosDark || '—'}\` |`);
}
out('');
out('#### Missing in iOS (Figma has them, iOS does not)');
out('');
const missingByFamily = {};
for (const r of parity.rows.filter(x => x.status === 'missing-ios')) {
  const fam = r.figmaName.split('/')[0];
  (missingByFamily[fam] = missingByFamily[fam] || []).push(r);
}
for (const [fam, rows] of Object.entries(missingByFamily)) {
  out(`**${fam}** — ${rows.length} missing:`);
  for (const r of rows) out(`- \`${r.figmaName}\` (Light \`${r.figmaLight}\`, Dark \`${r.figmaDark}\`)`);
  out('');
}

out('#### iOS-only (no Figma semantic equivalent)');
out('');
for (const c of parity.iosOnlyTokens) {
  out(`- \`${c.name}\` — Light \`${c.light}\` (raw \`${c.lightRaw}\`)${c.dark ? `, Dark \`${c.dark}\`` : ' — **no dark variant**'}`);
}
out('');

// Padding
out('### Padding (spacing)');
out('');
out('| Figma var | Figma value | iOS const | iOS value | Status |');
out('|---|---|---|---|---|');
for (const r of padRows) out(`| ${r.figma || '—'} | ${r.figmaVal !== null && r.figmaVal !== undefined ? r.figmaVal : '—'} | ${r.iosName || '—'} | ${r.iosVal !== null && r.iosVal !== undefined ? r.iosVal : '—'} | ${padStatus(r)} |`);
out('');
out('### Corner radius');
out('');
out('| Figma var | Figma value | iOS const | iOS value | Status |');
out('|---|---|---|---|---|');
for (const r of radRows) out(`| ${r.figma || '—'} | ${r.figmaVal !== null && r.figmaVal !== undefined ? r.figmaVal : '—'} | ${r.iosName || '—'} | ${r.iosVal !== null && r.iosVal !== undefined ? r.iosVal : '—'} | ${padStatus(r)} |`);
out('');
out('### Typography');
out('');
out('> [!warning]');
out('> Figma has **no typography Variables**. Type styles in Figma live as Text Styles, which the audit script can\'t cross-check programmatically against `LotusTypography.swift`. Token-level parity for typography requires a manual cross-reference.');
out('');
out('| iOS const | Family | Size |');
out('|---|---|---|');
for (const [n, family, size] of iosTypography) out(`| ${n} | ${family} | ${size}pt |`);
out('');
out('---');
out('');

// Adoption
out('## Adoption — repo total');
out('');
out(`- **Total Swift files scanned (with UI styling):** ${scan.totals.files}`);
out(`- **Tokenised references:** ${scan.totals.tokenised} (colour ${scan.patternCounts.tokenised_colour}, typography ${scan.patternCounts.tokenised_typography}, spacing ${scan.patternCounts.tokenised_spacing}, radius ${scan.patternCounts.tokenised_radius})`);
out(`- **Violation references:** ${scan.totals.violations} (legacy ${scan.totals.legacy}, hardcoded literal ${scan.totals.hardcoded})`);
out(`- **Tokenisation ratio:** ${(scan.totals.ratio * 100).toFixed(1)}%`);
out('');
out('```mermaid');
out('pie title References across the iOS app (UI files only)');
out(`    "Tokenised — Lotus.*" : ${scan.totals.tokenised}`);
out(`    "Legacy — jp* / Design2.0" : ${scan.totals.legacy}`);
out(`    "Hardcoded literals" : ${scan.totals.hardcoded}`);
out('```');
out('');

// By flow
out('## Adoption by flow');
out('');
const flows = Object.entries(scan.byFlow).sort((a, b) => b[1].ratio - a[1].ratio);
out('| Flow | Files | Tokenised | Violations | Ratio |');
out('|---|---|---|---|---|');
for (const [name, s] of flows) out(`| ${name} | ${s.files} | ${s.tokenised} | ${s.violations} | **${(s.ratio * 100).toFixed(0)}%** |`);
out('');
out('```mermaid');
out('xychart-beta');
out('    title "Tokenisation ratio by flow (%)"');
out(`    x-axis [${flows.map(([n]) => `"${n}"`).join(', ')}]`);
out('    y-axis "Ratio %" 0 --> 100');
out(`    bar [${flows.map(([, s]) => Math.round(s.ratio * 100)).join(', ')}]`);
out('```');
out('');

// By screen
out('## Adoption by screen');
out('');
out('Sorted by violation count (worst first). Underscored names are non-screen scan roots.');
out('');
out('| Screen | Flow | Files | Tokenised | Violations | Ratio |');
out('|---|---|---|---|---|---|');
const screens = Object.entries(scan.byScreen).sort((a, b) => b[1].violations - a[1].violations);
for (const [name, s] of screens) out(`| ${name} | ${s.flow} | ${s.files} | ${s.tokenised} | ${s.violations} | ${(s.ratio * 100).toFixed(0)}% |`);
out('');

// Top violations
out('## Top violations');
out('');
out('| Pattern | Count |');
out('|---|---|');
for (const k of ['legacy_jp_colour','hard_uicolor_rgb','hard_color_rgb','hard_color_named','hard_uicolor_system','hard_edgeinsets','hard_padding','hard_radius','hard_spacing','hard_font_system','hard_font_custom','hard_hex_init','legacy_design2_sem','legacy_design2_prim']) {
  const n = scan.patternCounts[k];
  if (n > 0) out(`| \`${k}\` | ${n} |`);
}
out('');
out('### Worst-offender files');
out('');
out('| File | Flow / Screen | Tokenised | Violations | Ratio |');
out('|---|---|---|---|---|');
for (const f of scan.worstFiles.slice(0, 15)) out(`| \`${f.rel}\` | ${f.flow} / ${f.screen} | ${f.tokenised} | ${f.violations} | ${(f.ratio * 100).toFixed(0)}% |`);
out('');

// Legacy
out('## Legacy colour systems');
out('');
out(`The \`jp*\` palette in \`Shared/JPCore/Extensions/UIColor+JP.swift\` accounts for **${scan.totals.legacy} references**. Concentrated in:`);
out('');
out('| File | Refs |');
out('|---|---|');
for (const f of (scan.topAffected.legacy_jp_colour || [])) out(`| \`${f.rel}\` | ${f.n} |`);
out('');

// Notable findings
const noDarkCount = ios.filter(c => !c.dark).length;
out('## Notable findings');
out('');
out('### 🔴 Critical');
out('');
out(`1. **\`Brand.JustparkGreen\` displays as \`#00A71D\` on P3-capable iPhones**, not \`#23A437\` as designed. The asset stores bytes \`0x23 0xA4 0x37\` but is tagged \`display-p3\`, so the OS interprets those numbers in the wider P3 gamut and renders a more saturated green than Figma intended. This is the visible "really saturated header" effect on Lotus-tokenised SwiftUI screens (e.g. ReservationV2) that doesn't show on legacy UIKit screens (which use \`.jpGreen\` = \`#1FA637\` raw RGB in extended sRGB).`);
out(`2. **\`Action.PrimaryDefault\` is \`#008000\`** in the asset catalog, with displayed-sRGB equivalent \`#0EA800\`. Should resolve to either grey-900 (Figma's new \`Action-App/Primary-Default\`) or brand green. Currently neither.`);
out(`3. **${noDarkCount} of ${ios.length} colorsets have no Dark Mode variant.** Apps in dark mode silently fall back to the light value across nearly half the palette.`);
out(`4. **\`radiusFull\` Figma = \`999\`, iOS = \`32\`.** Pills and fully-rounded badges look noticeably squarer than designed.`);
out('');
out('### 🟠 Structural');
out('');
out(`5. **Two different brand greens coexist.** Legacy UIKit screens use \`.jpGreen\` = \`#1FA637\` (the 2017 brand green, raw RGB → extended sRGB). New Lotus screens use \`Brand.JustparkGreen\` = \`#23A437\` raw bytes tagged P3 → displays as \`#00A71D\`. Three different greens, three different colour spaces, depending on the screen.`);
out(`6. **Figma's semantic Colour layer has expanded — iOS hasn't caught up.** ${cs.missingIos} Figma tokens have no iOS equivalent: the entire \`Tertiary\` action variant, \`Tapped\` states, \`Link-Default\`/\`Link-Hover\` within each alert family, \`Surface/Contrast\`, \`Text/Contrast\`.`);
out(`7. **Per-flow adoption is bimodal.** SwiftUI-first flows (Home ${Math.round(scan.byFlow.Home?.ratio * 100 || 0)}%, On-Demand ${Math.round(scan.byFlow['On-Demand']?.ratio * 100 || 0)}%, Auth ${Math.round(scan.byFlow['Auth & Onboarding']?.ratio * 100 || 0)}%) are well tokenised. UIKit-legacy areas (Shared & Infra ${Math.round(scan.byFlow['Shared & Infra']?.ratio * 100 || 0)}%, Account ${Math.round(scan.byFlow.Account?.ratio * 100 || 0)}%, Widget ${Math.round(scan.byFlow['Widget & Extensions']?.ratio * 100 || 0)}%) are not.`);
out('');
out('### 🟡 Type system');
out('');
out('8. `h2PoppinsLight` is `23pt` — every other H2 variant is `24pt`. Off-by-one bug.');
out('9. `h1Poppins` uses `Bold` (700) — Figma spec is SemiBold (600).');
out('');
out('---');
out('');

// Recommendations
out('## Recommendations');
out('');
out('### 🚨 Migrate iOS asset catalog from Display-P3 to sRGB');
out('');
out('**Why:** Figma, Android (Compose `Color(0xFF…)`), and Web (CSS hex) all use sRGB. iOS is the only platform tagging colours as `display-p3`. The result is a brand that looks subtly different across platforms, and visibly different across screens within the iOS app (Lotus P3 surfaces vs legacy sRGB surfaces — see finding #5).');
out('');
out('**What:** Re-tag every colorset under `Lotus/Sources/Lotus/Assets.xcassets/Lotus-Colour-Pallet/` from `"color-space": "display-p3"` to `"color-space": "srgb"`. Keep the same hex byte values. Validate visually on a real P3 iPhone afterwards — most JustPark colours are inside the sRGB gamut so the visual change is small (saturated greens become slightly less vivid; neutrals are virtually identical).');
out('');
out('**Mechanical fix:**');
out('');
out('```bash');
out('cd parkhub/ios/Lotus/Sources/Lotus/Assets.xcassets/Lotus-Colour-Pallet');
out('find . -name "Contents.json" -exec sed -i \'\' \'s/"display-p3"/"srgb"/g\' {} +');
out('# QA on a real P3-capable device before merging');
out('```');
out('');
out('Trade-off accepted: brand colours won\'t exploit the P3 gamut on modern iPhones. In exchange, the brand renders identically across iOS / Android / Web and matches Figma exactly. For a parking app this is the right call.');
out('');
out('### Other recommendations (lower priority)');
out('');
out('- **Fix `Action.PrimaryDefault`** — bring it back to the brand green (or grey-900 if following Figma\'s newer Action layer).');
out('- **Backfill Dark Mode variants** for the 22 colorsets currently missing one.');
out('- **Decide on the `Tertiary` action layer** — adopt Figma\'s expanded semantic system on iOS, or push back on Figma to drop the unused tokens.');
out('- **Migrate legacy UIKit headers off `.jpGreen`** — this is the biggest single source of brand-green inconsistency in the app.');
out('- **Update `radiusFull` to 999** to match Figma + Web.');
out('');
out('---');
out('');

// Methodology
out('## Methodology + caveats');
out('');
out(`- **Scan roots:** ${scan.scanRoots.map(r => `\`${r}\``).join(', ')}`);
out('- **Excluded:** `Lotus/`, `*Tests/`, `Ampli/`, `Screens/Debug/Lotus/`.');
out('- **Compliance counted by reference**, not file. Ratios are aggregate-of-refs, not aggregate-of-files.');
out('- **Token-parity scope:** colour, padding, corner radius. Typography listed but not auto-checked (Figma stores type as Text Styles, not Variables).');
out('- **Colour-space conversion:** iOS asset catalogs are tagged `display-p3`. The audit applies the standard P3→sRGB matrix transform (D65 white point) so the displayed values can be compared apples-to-apples with Figma\'s sRGB hex. Both displayed and raw bytes are shown in tables for transparency.');
out('- **Name-mapping is heuristic.** Figma uses kebab-case (`Primary-Default`); iOS uses camelCase (`PrimaryDefault`). Names are normalised for comparison; fundamental renames or restructured collections surface as `missing-ios` rows.');
out('- **Component-level parity not assessed in this version.** The skill does not yet detect a vanilla `Button` where `ButtonPrimary` should be used.');
out('');

const md = lines.join('\n');

// Output paths.
// Resolve the Lotus repo root from this script's location: <repo>/.claude/skills/lotus-audit-ios/scripts/build-report.mjs
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOTUS_REPO = path.resolve(__dirname, '..', '..', '..', '..');
const DATE = today;
let primary;
if (outOverride) {
  primary = path.resolve(outOverride);
} else {
  const PRIMARY_DIR = path.join(LOTUS_REPO, 'audits', 'ios');
  mkdirSync(PRIMARY_DIR, { recursive: true });
  primary = path.join(PRIMARY_DIR, `${DATE}.md`);
}
const primaryBase = primary.replace(/\.md$/, '');
let i = 2;
while (existsSync(primary)) { primary = `${primaryBase}-${i}.md`; i++; }
mkdirSync(path.dirname(primary), { recursive: true });
writeFileSync(primary, md);
console.log(`primary: ${primary}`);

// Mirror only when LOTUS_AUDIT_MIRROR is explicitly set — no magic vault detection.
// The vault-index update below will only fire if the mirror happens to land in
// the Olly-vault Audits folder, but that's a specific path match, not auto-discovery.
const MIRROR_DIR = process.env.LOTUS_AUDIT_MIRROR || null;
const VAULT_AUDITS = `${process.env.HOME}/Documents/Olly's Brain/Areas/JustPark/Projects/Lotus/Audits`;
if (MIRROR_DIR && existsSync(MIRROR_DIR)) {
  let mirror = path.join(MIRROR_DIR, `${DATE}.md`);
  const mbase = mirror.replace(/\.md$/, '');
  let j = 2;
  while (existsSync(mirror)) { mirror = `${mbase}-${j}.md`; j++; }
  copyFileSync(primary, mirror);
  console.log(`mirror: ${mirror}`);

  const indexPath = `${process.env.HOME}/Documents/Olly's Brain/Areas/JustPark/Projects/Lotus/_Index.md`;
  if (existsSync(indexPath) && mirror.startsWith(VAULT_AUDITS)) {
    const mirrorName = path.basename(mirror, '.md');
    const idx = readFileSync(indexPath, 'utf8');
    if (!idx.includes(`[[Audits/${mirrorName}]]`)) {
      const updated = idx.replace(/(## Audits\n(?:- .+\n)*)/, `$1- [[Audits/${mirrorName}]] — auto-generated\n`);
      writeFileSync(indexPath, updated);
      console.log(`index updated`);
    }
  }
}
