#!/usr/bin/env node
// Assemble the lotus-audit-web Markdown report.
//
// Inputs (env overrides shown; default to /tmp/<name>.json):
//   FIGMA_JSON         lotus-figma-tokens.json
//   WEB_TOKENS_JSON    web-tokens.json
//   PARITY_JSON        colour-parity-web.json
//   SCAN_JSON          web-scan.json
//   CANDIDATES_JSON    candidates-web.json
//   FIX_PROPOSALS_JSON fix-proposals-web.json     (optional, Stage 3 output)
//
// Output:
//   primary:  <lotus-repo>/audits/web/YYYY-MM-DD.md (or --out)
//   mirror:   $LOTUS_AUDIT_MIRROR/YYYY-MM-DD-web.md (if env set)
//   index:    Olly-vault _Index.md (only when mirror is in that vault)

import { readFileSync, writeFileSync, mkdirSync, existsSync, copyFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const figma  = JSON.parse(readFileSync(process.env.FIGMA_JSON       || '/tmp/lotus-figma-tokens.json', 'utf8'));
const web    = JSON.parse(readFileSync(process.env.WEB_TOKENS_JSON  || '/tmp/web-tokens.json', 'utf8'));
const parity = JSON.parse(readFileSync(process.env.PARITY_JSON      || '/tmp/colour-parity-web.json', 'utf8'));
const scan   = JSON.parse(readFileSync(process.env.SCAN_JSON        || '/tmp/web-scan.json', 'utf8'));

let candidates = null;
try { candidates = JSON.parse(readFileSync(process.env.CANDIDATES_JSON || '/tmp/candidates-web.json', 'utf8')); } catch {}

let fixProposals = null;
try { fixProposals = JSON.parse(readFileSync(process.env.FIX_PROPOSALS_JSON || '/tmp/fix-proposals-web.json', 'utf8')); } catch {}

let outOverride = null;
const outIdx = process.argv.indexOf('--out');
if (outIdx !== -1 && process.argv[outIdx + 1]) outOverride = process.argv[outIdx + 1];

// ===========================================================================

const today = new Date().toISOString().slice(0, 10);
const lines = [];
const out = (s = '') => lines.push(s);

const fc = name => figma.collections.find(c => c.collection === name);
const padCol = fc('Padding');
const radCol = fc('Corner Radius');
const typoCol = fc('Typography');

// Header
out(`# Lotus — Web Audit (${today})`);
out('');
out(`*Auto-generated by \`/lotus-audit-web\`. Source of truth: [Lotus design system Figma file](https://www.figma.com/design/YkS9s6Cz3EYdbr5UThzUKP/Lotus---Design-System).*`);
out('');
out(`*frontend commit:* \`${(scan.frontendCommit || 'unknown').slice(0,7)}\` · *justpark commit:* \`${(scan.justparkCommit || 'unknown').slice(0,7)}\` · *Figma snapshot:* \`${figma.generatedAt}\` · *Files scanned:* ${scan.totals.files}`);
out('');
out('---');
out('');

// Summary
const ratio = (scan.totals.ratio * 100).toFixed(0);
out('## Summary');
out('');
out('> [!summary]');
out(`> Lotus compliance across JustPark's customer-facing web surfaces sits at **${ratio}%** (${scan.totals.compliant} compliant references vs ${scan.totals.violations} violations across ${scan.totals.files} files). The dominant violation is **${scan.patternCounts.hard_px_scss || 0} raw \`Npx\` values** in SCSS — consistent with web Lotus having **no typography tokens yet** (${scan.patternCounts.hard_font_size || 0} hardcoded \`font-size:\` declarations confirm the gap). The headline candidates for new Figma tokens: **\`10px\`** (used ${(candidates?.candidates.spacing.find(c => c.value === 10)?.count) || '?' }× across web) and **\`20px\`** (used ${(candidates?.candidates.spacing.find(c => c.value === 20)?.count) || '?' }×) — both already exist on iOS as \`spacingSemiSmall\` and \`spacingXMedium\` but are not in Figma's Padding collection. Colour parity vs Figma: ${parity.summary.match} match, ${parity.summary.mismatch} mismatch, ${parity.summary.missingWeb} Figma tokens have no web equivalent (Figma's semantic layer has expanded far ahead of web's). Web is sRGB throughout — no colour-space conversion needed; raw hex byte values compare directly to Figma.`);
out('');
out('---');
out('');

// Scope
out('## Scope');
out('');
out('### Customer-facing apps scanned');
out('');
out('| App | Repo | Files | Tier |');
out('|---|---|---|---|');
for (const [name, app] of Object.entries(scan.byApp)) {
  out(`| \`${name}\` | parkhub/${name.startsWith('monolith') ? 'justpark' : 'frontend'} | ${app.files} | ${app.tier} |`);
}
out('');
out('### Explicitly out of scope');
out('');
out('- **Operator portals** — Luna (host portal), Solar (internal ops), Terra (business accounts), Enforcement. Different audience, separate Amplitude projects. A `lotus-audit-web-portals` skill is planned for these.');
out('- **`@justpark/ui` itself** — the design system *defines* tokens; it isn\'t a consumer of them.');
out('- **`browser-extension`** — internal dev tool (test-account login on `justpark.me`).');
out('- **Email templates** (`justpark/resources/views/emails/`, 343 files) — different styling rules (inline CSS for client compatibility); separate future audit.');
out('- **Admin / call centre / dashboard** Blade views.');
out('');
out('> [!warning] Storyblok-hosted pages (out of scope for code audit)');
out('> Marketing landing pages and brand partner themes (NCP, O2, etc.) live in Storyblok, not in this codebase. The audit can\'t directly measure their token compliance.');
out('>');
out('> **Storyblok is intentionally allowed to override Lotus tokens at runtime** via CSS custom properties (the `--lotus-*` variables exposed by `_colors.scss`). That\'s the designed mechanism for partner theming.');
out('>');
out('> Future token-architecture work should formalise *which* tokens are publicly overridable vs. which are internal — without that boundary, partner themes can reach into private surfaces and produce visual regressions.');
out('');
out('---');
out('');

// Token parity
out('## Token parity (Figma ↔ web)');
out('');

out('### Colours');
out('');
out(`Figma's semantic Colour collection has ${parity.rows.length} matchable tokens (\`Action-App/*\`, \`Surface/*\`, \`Text/*\`, \`Border/*\`, \`Brand/*\`, \`Alerts/*\`). Web's \`_colors.scss\` has ${Object.keys(web.semantic).length} semantic tokens.`);
out('');
out('| Status | Count |');
out('|---|---|');
out(`| ✅ Match | ${parity.summary.match} |`);
out(`| ❌ Value mismatch | ${parity.summary.mismatch} |`);
out(`| ❌ Missing in web | ${parity.summary.missingWeb} |`);
out(`| ⚠️ Web-only (no Figma equivalent) | ${parity.summary.webOnly} |`);
out('');

if (parity.rows.filter(r => r.status === 'mismatch').length > 0) {
  out('#### Mismatches');
  out('');
  out('| Figma | Web | Figma value | Web value |');
  out('|---|---|---|---|');
  for (const r of parity.rows.filter(r => r.status === 'mismatch')) {
    out(`| ${r.figmaName} | ${r.webName} | \`${r.figmaLight}\` | \`${r.webHex || '—'}\` |`);
  }
  out('');
}

out('#### Missing in web (top by family)');
out('');
const missingByFamily = {};
for (const r of parity.rows.filter(r => r.status === 'missing-web')) {
  const fam = r.figmaName.split('/')[0];
  (missingByFamily[fam] = missingByFamily[fam] || []).push(r);
}
for (const [fam, list] of Object.entries(missingByFamily)) {
  out(`**${fam}** — ${list.length} missing: ${list.map(r => `\`${r.figmaName}\``).join(', ')}`);
  out('');
}

out('### Spacing (padding)');
out('');
out(`Web \`_spacing.scss\` has ${Object.keys(web.spacing).length} tokens. Figma \`Padding\` has ${padCol?.vars.length || 0}.`);
out('');
out('| Figma var | Figma value | Web token | Web value | Status |');
out('|---|---|---|---|---|');
const webSpacingByValue = Object.fromEntries(Object.entries(web.spacing).map(([k, v]) => [v, k]));
if (padCol) {
  for (const v of padCol.vars) {
    const val = Object.values(v.valuesByMode)[0]?.resolved;
    const webName = webSpacingByValue[val];
    const status = webName ? '✅ match' : '❌ missing in web';
    out(`| ${v.name} | ${val} | ${webName ? `\`$${webName}\`` : '—'} | ${webName ? val : '—'} | ${status} |`);
  }
}
// Web-only spacing
const figmaSpaceValues = new Set(padCol?.vars.map(v => Object.values(v.valuesByMode)[0]?.resolved) || []);
for (const [name, val] of Object.entries(web.spacing)) {
  if (!figmaSpaceValues.has(val)) out(`| — | — | \`$${name}\` | ${val} | ⚠️ web-only |`);
}
out('');

out('### Corner radius');
out('');
out(`Web \`_radius.scss\` has ${Object.keys(web.radius).length} tokens. Figma \`Corner Radius\` has ${radCol?.vars.length || 0}.`);
out('');
out('| Figma var | Figma value | Web token | Web value | Status |');
out('|---|---|---|---|---|');
const webRadiusByValue = Object.fromEntries(Object.entries(web.radius).map(([k, v]) => [v, k]));
if (radCol) {
  for (const v of radCol.vars) {
    const val = Object.values(v.valuesByMode)[0]?.resolved;
    const webName = webRadiusByValue[val];
    const status = webName ? '✅ match' : '❌ missing in web';
    out(`| ${v.name} | ${val} | ${webName ? `\`$${webName}\`` : '—'} | ${webName ? val : '—'} | ${status} |`);
  }
}
const figmaRadiusValues = new Set(radCol?.vars.map(v => Object.values(v.valuesByMode)[0]?.resolved) || []);
for (const [name, val] of Object.entries(web.radius)) {
  if (!figmaRadiusValues.has(val)) out(`| — | — | \`$${name}\` | ${val} | ⚠️ web-only |`);
}
out('');

out('### Typography');
out('');
out('> [!warning] Web has no typography tokens');
out('> The Lotus SCSS layer in `@justpark/ui/src/scss/lotus/` defines no typography tokens today — no `_typography.scss`, no `font-size/*` or `font-family/*` variables. Web engineers freestyle font sizes and weights across the codebase.');
out('>');
out(`> Figma's Typography collection has ${typoCol?.vars.length || 0} atomic tokens ready to be mirrored (\`font-size/*\`, \`line-height/*\`, \`font-family/*\`, \`font-style/*\`). iOS has 21 composed type styles.`);
out('>');
out(`> The scan found **${scan.patternCounts.hard_font_size || 0} hardcoded \`font-size:\` declarations** in customer-facing web. Closing this gap is one of the highest-leverage Lotus investments on web today.`);
out('');
out('---');
out('');

// Adoption
out('## Adoption — customer-facing surface total');
out('');
out(`- **Total files scanned:** ${scan.totals.files}`);
out(`- **Compliant references:** ${scan.totals.compliant}`);
out(`- **Violation references:** ${scan.totals.violations} (legacy ${scan.totals.legacy}, hardcoded literal ${scan.totals.hardcoded})`);
out(`- **Compliance ratio:** ${(scan.totals.ratio * 100).toFixed(1)}%`);
out('');
out('```mermaid');
out('pie title References across customer-facing web');
out(`    "Compliant — Lotus tokens / @justpark/ui" : ${scan.totals.compliant}`);
out(`    "Legacy — _jpColors etc." : ${scan.totals.legacy}`);
out(`    "Hardcoded literals" : ${scan.totals.hardcoded}`);
out('```');
out('');

// By app
out('## Adoption by app');
out('');
const apps = Object.entries(scan.byApp).sort((a, b) => b[1].ratio - a[1].ratio);
out('| App | Tier | Files | Compliant | Legacy | Hardcoded | Ratio |');
out('|---|---|---|---|---|---|---|');
for (const [name, s] of apps) {
  out(`| \`${name}\` | ${s.tier} | ${s.files} | ${s.compliant} | ${s.legacy} | ${s.hardcoded} | **${(s.ratio * 100).toFixed(0)}%** |`);
}
out('');
out('```mermaid');
out('xychart-beta');
out('    title "Compliance ratio by app (%)"');
out(`    x-axis [${apps.map(([n]) => `"${n}"`).join(', ')}]`);
out('    y-axis "Ratio %" 0 --> 100');
out(`    bar [${apps.map(([, s]) => Math.round(s.ratio * 100)).join(', ')}]`);
out('```');
out('');

// Worst files
out('## Worst-offender files');
out('');
out('| File | App | Violations | Compliant | Ratio |');
out('|---|---|---|---|---|');
for (const f of scan.worstFiles.slice(0, 15)) {
  out(`| \`${f.rel}\` | ${f.app} | ${f.violations} | ${f.compliant} | ${(f.ratio * 100).toFixed(0)}% |`);
}
out('');

// Top violations
out('## Top violation patterns');
out('');
out('| Pattern | Count |');
out('|---|---|');
for (const [k, n] of Object.entries(scan.patternCounts).filter(([k]) => !k.startsWith('compliant_')).sort((a, b) => b[1] - a[1])) {
  if (n > 0) out(`| \`${k}\` | ${n} |`);
}
out('');
out('---');
out('');

// Token candidates
if (candidates) {
  out('## Token candidates from web');
  out('');
  out(`Hardcoded values used **${candidates.thresholds.MIN_COLOUR}+ times** across customer-facing web, classified against the existing Figma + web Lotus token sets. Definition files (\`_colorPrimitives.scss\`, \`_jpColors.scss\`, etc.) excluded.`);
  out('');
  out('- **🔁 use-existing-token** — the value matches an existing token. Adoption gap.');
  out('- **🎯 near-miss** — within 1pt of an existing token. Typo / off-by-one.');
  out('- **➕ new-candidate** — not close to anything. Worth proposing as a new Figma token.');
  out('');

  const sections = [
    { key: 'spacing', title: 'Spacing', fmt: v => `${v}px`, min: candidates.thresholds.MIN_SPACING },
    { key: 'fontSize', title: 'Font size', fmt: v => `${v}px`, min: candidates.thresholds.MIN_FONT_SIZE },
    { key: 'radius', title: 'Corner radius', fmt: v => `${v}px`, min: candidates.thresholds.MIN_RADIUS },
    { key: 'colour', title: 'Colour (hex literals)', fmt: v => v, min: candidates.thresholds.MIN_COLOUR }
  ];
  for (const { key, title, fmt, min } of sections) {
    const list = candidates.candidates[key] || [];
    out(`### ${title}`);
    out('');
    if (list.length === 0) { out(`No candidates above threshold (${min}+ occurrences).`); out(''); continue; }
    out('| Status | Value | Occurrences | Nearest existing | Top files |');
    out('|---|---|---|---|---|');
    for (const c of list.slice(0, 15)) {
      const icon = c.status === 'use-existing-token' ? '🔁' : c.status === 'near-miss' ? '🎯' : '➕';
      const nearest = c.nearest != null ? `\`${fmt(c.nearest)}\`` : '—';
      out(`| ${icon} ${c.status} | \`${fmt(c.value)}\` | ${c.count} | ${nearest} | ${c.topFiles.slice(0, 2).map(f => `\`${f}\``).join(', ') || '—'} |`);
    }
    if (list.length > 15) out(`\n_(${list.length - 15} more candidates not shown)_\n`);
    out('');
  }
}

// Suggested fixes
if (fixProposals?.proposals?.length) {
  out('## Suggested fixes — worst-offender files');
  out('');
  out(`Generated by spawning a sub-agent per worst-offender file. ${fixProposals.proposals.length} files analysed.`);
  out('');
  for (const fileResult of fixProposals.proposals) {
    out(`### \`${fileResult.file}\``);
    out('');
    if (fileResult.error) { out(`> [!warning] Sub-agent failed: ${fileResult.error}`); out(''); continue; }
    if (!fileResult.suggestions?.length) { out('_(No actionable suggestions.)_'); out(''); continue; }
    out('| Line | Current | Proposed | Token | Confidence | Note |');
    out('|---|---|---|---|---|---|');
    for (const s of fileResult.suggestions) {
      const note = (s.note || '').replace(/\|/g, '\\|');
      const cur = (s.current || '').replace(/\|/g, '\\|');
      const prop = (s.proposed || '').replace(/\|/g, '\\|');
      out(`| ${s.line || '—'} | \`${cur}\` | \`${prop}\` | \`${s.tokenUsed || '—'}\` | ${s.confidence || '—'} | ${note} |`);
    }
    out('');
  }
}

// Notable findings
out('## Notable findings');
out('');
out('### 🔴 Critical');
out('');
out(`1. **No typography tokens on web.** ${scan.patternCounts.hard_font_size || 0} hardcoded \`font-size:\` declarations. iOS has 21 composed type styles; Figma has 23 atomic typography tokens. Web is the outlier — and the surface where typography variation hurts the brand most (because the consumer sees web text more than iOS labels).`);
out(`2. **\`10px\` and \`20px\` spacing values used over 1,500 times combined** in web, but neither is in Figma's Padding collection. iOS has these tokens (\`spacingSemiSmall\`, \`spacingXMedium\`). Either add to Figma (consistent across platforms) or migrate web to nearest existing tokens.`);
out(`3. **${parity.summary.missingWeb} Figma semantic colour tokens missing on web.** Same expanded \`Tertiary\` / \`Tapped\` / \`Link-*\` semantic layer that iOS hasn't caught up on.`);
out('');
out('### 🟠 Structural');
out('');
out(`4. **Web is sRGB throughout.** No P3 drift like iOS. Brand colours render exactly as Figma intends — but values diverge in some cases (see Colour mismatches table).`);
out(`5. **Storyblok runtime override surface is undocumented.** \`_colors.scss\` exposes every semantic token as \`var(--lotus-*, fallback)\`. Storyblok partner themes can override these at runtime — that's the designed mechanism. But there's no documented list of *which* CSS variables are public override surface vs. internal. Partner themes today can reach into private tokens and produce regressions.`);
out(`6. **Legacy \`_jpColors.scss\` still alive** but small footprint (${scan.totals.legacy} refs vs ${scan.totals.compliant} compliant). Cleanup opportunity now that adoption is mostly via Lotus tokens or hardcoded literals.`);
out('');
out('---');
out('');

// Recommendations
out('## Recommendations');
out('');
out('### 🚨 Add typography tokens to web Lotus');
out('');
out(`Highest single-investment improvement. Mirror Figma's atomic typography Variables into \`@justpark/ui/src/scss/lotus/_typography.scss\`. Web engineers then have a token surface to migrate the ${scan.patternCounts.hard_font_size || '600+'} hardcoded \`font-size:\` declarations onto.`);
out('');
out('### Decide on `10px` and `20px` spacing');
out('');
out('iOS has them, web uses them prolifically (1,500+ occurrences combined), Figma doesn\'t. Three options:');
out('1. **Add to Figma** — easiest path; makes web/iOS consistent with Figma being canonical.');
out('2. **Migrate web call sites to existing tokens** — `10px` → `$xs` (8) or `$s` (12); `20px` → `$m` (16) or `$l` (24). Larger migration burden.');
out('3. **Keep web-only** — define `$semi-small` (10) and `$x-medium` (20) in web Lotus, accept platform divergence with Figma.');
out('');
out('### Other');
out('');
out(`- **Document the Storyblok override surface** — formalise which CSS custom properties partner themes can override, separate from internal tokens.`);
out(`- **Remove \`_jpColors.scss\`** once the remaining ${scan.totals.legacy} legacy references migrate.`);
out(`- **Pursue colour parity** — ${parity.summary.missingWeb} Figma tokens missing in web mostly relate to the new \`Tertiary\`, \`Tapped\`, \`Link-*\` semantic layer Figma added. Either adopt or push back on Figma to drop them.`);
out('');
out('---');
out('');

// Methodology
out('## Methodology + caveats');
out('');
out(`- **Customer-facing scan targets:** \`frontend/web\`, \`frontend/pay\`, \`justpark/resources/views/{mobile,site,bookings,listings,referrals,auth,static,npp}\`, \`justpark/public/assets/scss/{app,site}\`.`);
out('- **Excluded:** operator portals (Luna, Solar, Terra, Enforcement), internal admin / call centre / dashboard, email templates (different audit), `@justpark/ui` itself (the definitions), browser extension (internal dev tool), Storyblok-hosted pages (CMS-managed, scanned via API in a future audit).');
out('- **Compliance counted by reference**, not file. Ratios are aggregate-of-refs, not aggregate-of-files.');
out('- **Web is sRGB throughout.** No colour-space conversion needed (unlike iOS where P3 tags create displayed-vs-stored divergence).');
out('- **Compliant signals:** SCSS `@use \'@justpark/ui/src/scss/lotus/*\'`, references like `colors.$text-primary`, CSS `var(--lotus-*)`, JSX `from \'@justpark/ui\'`.');
out('- **Token-parity scope:** colour, padding, corner radius. Typography listed but unauditable until web Lotus adds tokens.');
out('- **Definition files excluded from violation scanning:** `_colorPrimitives.scss`, `_colors.scss`, `_spacing.scss`, `_radius.scss`, `_jpColors.scss`, `_variables.scss`, `_lotusMixins.scss`, `_utilities.scss` — these *define* tokens; their internal literals shouldn\'t be flagged.');
out('');

// ===========================================================================

const md = lines.join('\n');

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LOTUS_REPO = path.resolve(__dirname, '..', '..', '..', '..');

let primary;
if (outOverride) primary = path.resolve(outOverride);
else {
  const dir = path.join(LOTUS_REPO, 'audits', 'web');
  mkdirSync(dir, { recursive: true });
  primary = path.join(dir, `${today}.md`);
}
const primaryBase = primary.replace(/\.md$/, '');
let i = 2;
while (existsSync(primary)) { primary = `${primaryBase}-${i}.md`; i++; }
mkdirSync(path.dirname(primary), { recursive: true });
writeFileSync(primary, md);
console.log(`primary: ${primary}`);

const MIRROR_DIR = process.env.LOTUS_AUDIT_MIRROR || null;
const VAULT_AUDITS = `${process.env.HOME}/Documents/Olly's Brain/Areas/JustPark/Projects/Lotus/Audits`;
if (MIRROR_DIR && existsSync(MIRROR_DIR)) {
  let mirror = path.join(MIRROR_DIR, `${today}-web.md`);
  const mbase = mirror.replace(/\.md$/, '');
  let j = 2;
  while (existsSync(mirror)) { mirror = `${mbase}-${j}.md`; j++; }
  copyFileSync(primary, mirror);
  console.log(`mirror: ${mirror}`);

  const indexPath = `${process.env.HOME}/Documents/Olly's Brain/Areas/JustPark/Projects/Lotus/_Index.md`;
  if (existsSync(indexPath) && mirror.startsWith(VAULT_AUDITS)) {
    const mirrorName = path.basename(mirror, '.md');
    const idx = readFileSync(indexPath, 'utf8');
    if (!idx.includes(`[[Audits/${mirrorName}]]`)) {
      const updated = idx.replace(/(## Audits\n(?:- .+\n)*)/, `$1- [[Audits/${mirrorName}]] — auto-generated\n`);
      writeFileSync(indexPath, updated);
      console.log(`index updated`);
    }
  }
}
